apiVersion: v1
kind: Service
metadata:
  name: callcode-session-s1
  labels:
    app: callcode
    session-id: s1
spec:
  selector:
    app: callcode
    session-id: s1
  ports:
  - name: http
    port: 80
    targetPort: 5173
    protocol: TCP
  - name: websocket
    port: 8080
    targetPort: 8080
    protocol: TCP
