apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: callcode-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.call-code.local"
